#设置端口号
server:
  port: 7003
#项目名称(项目命名成不能使用下横杠) 用于以后spring cloud服务的查找
spring:
  application:
    name: huahua-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.234.128:3306/huahua_base?characterEncoding=UTF-8
    username: root
    password: '0523'
#jpa的配置
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
#mybatis的映射路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
#日志级别
logging:
  level:
    root: info
#注册到eureka服务中
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
