package com.huahua.base.dao;

import com.huahua.base.dto.LabelDO;
import com.huahua.base.dto.LabelDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface LabelDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    long countByExample(LabelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int deleteByExample(LabelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int insert(LabelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int insertSelective(LabelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    List<LabelDO> selectByExample(LabelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    LabelDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") LabelDO record, @Param("example") LabelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int updateByExample(@Param("record") LabelDO record, @Param("example") LabelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int updateByPrimaryKeySelective(LabelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_label
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int updateByPrimaryKey(LabelDO record);
}