package com.huahua.base.dao;

import com.huahua.base.dto.UlDOExample;
import com.huahua.base.dto.UlDOKey;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UlDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ul
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    long countByExample(UlDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ul
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int deleteByExample(UlDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ul
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int deleteByPrimaryKey(UlDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ul
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int insert(UlDOKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ul
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int insertSelective(UlDOKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ul
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    List<UlDOKey> selectByExample(UlDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ul
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") UlDOKey record, @Param("example") UlDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_ul
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    int updateByExample(@Param("record") UlDOKey record, @Param("example") UlDOExample example);
}