server: 
  port: 9002
spring: 
  application:  
    name: huahua-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.234.130:3306/huahua_recruit?useUnicode=true&characterEncoding=UTF8
    username: root
    password: '0523'
  jpa: 
    database: MySQL
    show-sql: true
