package com.huahua.base.dto;

public class UlDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ul.labelid
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    private String labelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_ul.userid
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ul.labelid
     *
     * @return the value of tb_ul.labelid
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    public String getLabelid() {
        return labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ul.labelid
     *
     * @param labelid the value for tb_ul.labelid
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    public void setLabelid(String labelid) {
        this.labelid = labelid == null ? null : labelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_ul.userid
     *
     * @return the value of tb_ul.userid
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_ul.userid
     *
     * @param userid the value for tb_ul.userid
     *
     * @mbg.generated Thu Apr 11 14:58:54 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}